repos:
  - repo: local
    hooks:
      - id: ruff-checker
        name: ruff-checker
        entry: ruff check
        language: python
        types: [ python ]
        args: [ --fix ]

      - id: ruff-formatter
        name: ruff-formatter
        entry: ruff format
        language: python
        types: [ python ]
        args: []

      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [ python ]
        args: []
