# Generated by Django 5.0.6 on 2024-06-26 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalogs', '0002_advert_advert_price_gte_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('origin', models.ImageField(upload_to='images/adverts/', verbose_name='origin')),
                (
                    'order_num',
                    models.PositiveIntegerField(
                        help_text='Image with order value as 0 will be cover image. Other images will be extra images.',
                        verbose_name='order',
                    ),
                ),
                (
                    'advert',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='image_set',
                        to='catalogs.advert',
                        verbose_name='advert',
                    ),
                ),
            ],
            options={
                'verbose_name': 'advert image',
                'verbose_name_plural': 'advert images',
                'ordering': ('advert', 'order_num'),
            },
        ),
        migrations.AddConstraint(
            model_name='advertimage',
            constraint=models.UniqueConstraint(fields=('advert', 'order_num'), name='unique_advert_and_order_num'),
        ),
    ]
