# Generated by Django 5.0.6 on 2024-09-04 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalogs', '0002_advert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation')),
                ('file', models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='file')),
                ('type', models.PositiveIntegerField(choices=[(0, 'main'), (1, 'extra')], verbose_name='type')),
                (
                    'advert',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='images',
                        to='catalogs.advert',
                        verbose_name='advert',
                    ),
                ),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
    ]
