# Generated by Django 5.1.1 on 2024-09-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0003_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraImage",
            fields=[],
            options={
                "verbose_name": "Extra Image",
                "verbose_name_plural": "Extra Image",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalogs.image",),
        ),
        migrations.CreateModel(
            name="MainImage",
            fields=[],
            options={
                "verbose_name": "Main Image",
                "verbose_name_plural": "Main Images",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("catalogs.image",),
        ),
    ]
