# Generated by Django 5.0.6 on 2024-09-23 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalogs', '0004_extraimage_mainimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='availability',
            field=models.PositiveIntegerField(
                choices=[(0, 'is available'), (1, 'is not available'), (2, 'to order')],
                default=0,
                verbose_name='availability',
            ),
        ),
        migrations.AddField(
            model_name='advert',
            name='delivery_comment',
            field=models.TextField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(512)],
                verbose_name='delivery comment',
            ),
        ),
        migrations.AddField(
            model_name='advert',
            name='location',
            field=models.CharField(default='-', max_length=100, verbose_name='location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='payment_card',
            field=models.CharField(
                default='0000 0000 0000 0000',
                max_length=19,
                validators=[
                    django.core.validators.RegexValidator(
                        '^\\d{4} \\d{4} \\d{4} \\d{4}$',
                        code='invalid_card_number',
                        message='Card number should be in the such style: "0000 0000 0000 0000".',
                    )
                ],
                verbose_name='payment card number',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='payment_comment',
            field=models.TextField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(512)],
                verbose_name='payment comment',
            ),
        ),
        migrations.AddField(
            model_name='advert',
            name='payment_method',
            field=models.PositiveIntegerField(
                choices=[(0, 'on card'), (1, 'in cash')], default=0, verbose_name='preferring payment method'
            ),
        ),
        migrations.AddField(
            model_name='advert',
            name='unit',
            field=models.PositiveIntegerField(
                choices=[(0, 'g'), (1, 'kg'), (2, 't'), (3, 'cm³'), (4, 'dm³'), (5, 'm³'), (6, 'ml'), (7, 'l')],
                default=1,
                verbose_name='unit',
            ),
            preserve_default=False,
        ),
    ]
