# Generated by Django 5.0.6 on 2024-07-09 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalogs', '0005_remove_category_is_displayed_remove_category_slug'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertAddress',
            fields=[
                (
                    'address_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='utils.address',
                    ),
                ),
                (
                    'advert',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to='catalogs.advert', verbose_name='advert'
                    ),
                ),
            ],
            options={
                'verbose_name': 'advert address',
                'verbose_name_plural': 'advert addresses',
                'ordering': ('advert',),
            },
            bases=('utils.address',),
        ),
    ]
