# Generated by Django 5.0.6 on 2024-09-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalogs', '0005_advert_availability_advert_delivery_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='nova_post',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='pickup',
        ),
        migrations.AddField(
            model_name='advert',
            name='delivery_method',
            field=models.PositiveIntegerField(
                choices=[
                    (1, 'pickup'),
                    (2, 'nova post'),
                    (4, 'courier'),
                    (3, 'pickup, nova post'),
                    (5, 'pickup, courier'),
                    (6, 'nova post, courier'),
                    (7, 'pickup, nova post, courier'),
                ],
                default=4,
                verbose_name='delivery methods',
            ),
        ),
    ]
