# Generated by Django 5.0.6 on 2024-07-09 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('catalogs', '0006_advertaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='address',
        ),
    ]
