# Generated by Django 5.0.6 on 2024-09-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalogs', '0006_remove_advert_courier_remove_advert_nova_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='availability',
            field=models.CharField(
                choices=[('available', 'is available'), ('not_available', 'is not available'), ('order', 'to order')],
                default='available',
                max_length=20,
                verbose_name='availability',
            ),
        ),
        migrations.AlterField(
            model_name='advert',
            name='delivery_method',
            field=models.CharField(
                choices=[('pickup', 'pickup'), ('nova_post', 'nova post'), ('courier', 'courier')],
                default='courier',
                max_length=10,
                verbose_name='delivery methods',
            ),
        ),
        migrations.AlterField(
            model_name='advert',
            name='payment_method',
            field=models.CharField(
                choices=[('card', 'on card'), ('cash', 'in cash')],
                default='card',
                max_length=5,
                verbose_name='preferring payment method',
            ),
        ),
        migrations.AlterField(
            model_name='advert',
            name='unit',
            field=models.CharField(
                choices=[
                    ('g', 'g'),
                    ('kg', 'kg'),
                    ('t', 't'),
                    ('cm3', 'cm³'),
                    ('dm3', 'dm³'),
                    ('m3', 'm³'),
                    ('ml', 'ml'),
                    ('l', 'l'),
                ],
                max_length=5,
                verbose_name='unit',
            ),
        ),
    ]
