# Generated by Django 5.0.6 on 2024-09-30 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('catalogs', '0007_alter_advert_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='quantity',
        ),
    ]
