# Generated by Django 5.0.6 on 2024-07-09 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalogs', '0007_remove_advert_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertaddress',
            name='advert',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='address',
                to='catalogs.advert',
                verbose_name='advert',
            ),
        ),
    ]
