# Generated by Django 5.0.6 on 2024-09-30 15:02

import django.contrib.postgres.fields
import functools
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalogs', '0008_remove_advert_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='advert',
            name='payment_methods',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(choices=[('card', 'on card'), ('cash', 'in cash')], max_length=5),
                default=functools.partial(list, *(['card'],), **{}),
                size=2,
                verbose_name='preferring payment method',
            ),
        ),
    ]
