# Generated by Django 5.0.6 on 2024-07-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalogs', '0008_alter_advertaddress_advert'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='use_courier',
            field=models.BooleanField(default=True, verbose_name='courier'),
        ),
        migrations.AddField(
            model_name='advert',
            name='use_nova_post',
            field=models.BooleanField(default=False, verbose_name='nova post'),
        ),
        migrations.AddField(
            model_name='advert',
            name='use_pickup',
            field=models.BooleanField(default=False, verbose_name='pickup'),
        ),
    ]
