# Generated by Django 5.0.6 on 2024-09-30 15:06

import django.contrib.postgres.fields
import functools
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalogs', '0009_remove_advert_payment_method_advert_payment_methods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='delivery_method',
        ),
        migrations.AddField(
            model_name='advert',
            name='delivery_methods',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[('pickup', 'pickup'), ('nova_post', 'nova post'), ('courier', 'courier')], max_length=10
                ),
                default=functools.partial(list, *(['courier'],), **{}),
                size=3,
                verbose_name='delivery methods',
            ),
        ),
    ]
