# Generated by Django 5.0.6 on 2024-10-01 13:42

import catalogs.validators
import django.contrib.postgres.fields
import functools
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalogs', '0010_remove_advert_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='delivery_methods',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[('pickup', 'pickup'), ('nova_post', 'nova post'), ('courier', 'courier')], max_length=10
                ),
                default=functools.partial(list, *(['courier'],), **{}),
                size=3,
                validators=[catalogs.validators.validate_array_elements_uniqueness],
                verbose_name='delivery methods',
            ),
        ),
        migrations.AlterField(
            model_name='advert',
            name='payment_methods',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(choices=[('card', 'on card'), ('cash', 'in cash')], max_length=5),
                default=functools.partial(list, *(['card'],), **{}),
                size=2,
                validators=[catalogs.validators.validate_array_elements_uniqueness],
                verbose_name='preferring payment method',
            ),
        ),
    ]
