# Generated by Django 5.0.6 on 2024-10-01 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('catalogs', '0011_alter_advert_delivery_methods_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='type',
        ),
    ]
