# Generated by Django 5.0.6 on 2024-06-25 13:34

import catalogs.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('title', models.CharField(max_length=100, unique_for_date='created_at', verbose_name='title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='price')),
                ('descr', models.TextField(blank=True, null=True, verbose_name='description')),
                ('address', models.CharField(max_length=256, verbose_name='address')),
                ('grades', models.JSONField(default=catalogs.models._get_default_grades, verbose_name='grades')),
                ('is_displayed', models.BooleanField(default=True, verbose_name='displayed')),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='catalogs.category', verbose_name='category'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user'
                    ),
                ),
            ],
            options={
                'verbose_name': 'advert',
                'verbose_name_plural': 'adverts',
                'ordering': ('is_displayed', 'created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='advert',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='price_gte_0'),
        ),
    ]
