# Generated by Django 5.0.6 on 2024-07-05 11:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('catalogs', '0004_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_displayed',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
