# Generated by Django 5.0.6 on 2024-07-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalogs', '0009_advert_use_courier_advert_use_nova_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='grades',
        ),
        migrations.AlterField(
            model_name='advert',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
