# Generated by Django 5.0.6 on 2024-07-12 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation')),
                ('region', models.CharField(max_length=100, verbose_name='region')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('village', models.CharField(blank=True, max_length=100, null=True, verbose_name='village')),
                ('street', models.CharField(max_length=100, verbose_name='street')),
                ('number', models.CharField(max_length=10, verbose_name='number')),
                ('object_id', models.PositiveIntegerField()),
                (
                    'content_type',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
                ),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
    ]
