name: Django Tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ "3.11" ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install
    - name: Build PostgreSQL image and run its container.
      run: |
        docker build -t test-db docker/postgres/
        docker run -e POSTGRES_DB=postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 --name db -d test-db

    - name: Wait for PostgreSQL to be ready
      run: |
        until docker exec db pg_isready; do sleep 1; done

    - name: Set up environments and run tests
      env:
        DJANGO_SETTINGS_ENV: "dev"
        DJANGO_SECRET_KEY: "django_secret_key_for_test"
        POSTGRES_DB: "postgres"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
      run: |
        cd src
        python manage.py test